estofadora/client/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.client.views',
    url(r'^(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^listar/$', 'list', name='list'),
    url(r'^(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^(?P<pk>\d+)/itens/', 'list_items', name='list_items'),
    url(r'^$', 'add', name='add'),
)

estofadora/item/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.item.views',
    url(r'^(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^listar/$', 'list', name='list'),
    url(r'^(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^(?P<pk>\d+)/imagens/', 'image_list', name='image_list'),
    url(r'^imagens/(?P<pk>\d+)/remover/', 'image_delete', name='image_delete'),
    url(r'^$', 'add', name='add'),
)

estofadora/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'estofadora.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^cliente/', include('estofadora.client.urls', namespace='client')),
    url(r'^item/', include('estofadora.item.urls', namespace='item')),
    url(r'^login/', include('estofadora.login.urls', namespace='login')),
    url(
        r'^relatorios/',
        include('estofadora.statement.urls', namespace='statement')
    ),
    url(r'^conta/', include('estofadora.bills.urls', namespace='bills')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('estofadora.core.urls', namespace='core')),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

estofadora/client/models.py
# conding: utf-8
from django.db import models


class Client(models.Model):

    name = models.CharField('Nome', max_length=200)
    email = models.EmailField('Email', unique=True, blank=True)
    adress = models.CharField(
        u'Endereço', max_length=256
    )
    telephone1 = models.CharField('Telefone 1', max_length=15)
    telephone2 = models.CharField('Telefone 2', max_length=15, blank=True)
    is_active = models.BooleanField(u'Está ativo?', default=True)
    date_join = models.DateTimeField('Data de cadastro', auto_now_add=True)

    class Meta:
        ordering = ['date_join']
        verbose_name = ('cliente')
        verbose_name_plural = ('clientes')

    def __str__(self):
        return self.name

estofadora/client/forms.py
# conding: utf-8
from django import forms
from .models import Client


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = [
            'name', 'adress', 'email', 'telephone1', 'telephone2', 'is_active'
        ]

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['adress'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['telephone1'].widget.attrs.update(
            {'class': 'form-control'}
        )
        self.fields['telephone2'].widget.attrs.update(
            {'class': 'form-control'}
        )

estofadora/client/views.py
# conding: utf-8
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from estofadora.item.models import Item

from .forms import ClientForm
from .models import Client


@login_required
def add(request):
    context = {}

    if request.method == 'POST':

        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cliente cadastrado com sucesso!')
            return redirect('client:list')
    else:
        form = ClientForm()

    context['form'] = form
    context['section'] = 'client_add'
    return render(request, 'client/add.html', context)


@login_required
def edit(request, pk):
    context = {}
    client = get_object_or_404(Client, pk=pk)

    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cliente alterado com sucesso!')
            return redirect(reverse('client:list'))
    else:
        form = ClientForm(instance=client)

    context['form'] = form
    context['client'] = client
    return render(request, 'client/edit.html', context)


@login_required
def list(request):
    context = {}

    if request.method == 'POST':
        client_name = request.POST.get('name')
        clients = Client.objects.filter(
            name__icontains=client_name
        ).order_by('name')

    else:
        clients = Client.objects.all().order_by('name')

    context['clients'] = clients
    context['section'] = 'clients'
    return render(request, 'client/list.html', context)


@login_required
def delete(request, pk):
    client = get_object_or_404(Client, pk=pk)
    client.delete()
    messages.success(request, 'Cliente removido com sucesso!')
    return redirect(reverse('client:list'))


@login_required
def list_items(request, pk):
    context = {}

    client = get_object_or_404(Client, pk=pk)
    items = Item.objects.filter(client=client)

    context['items'] = items
    context['client'] = client
    context['amount'] = len(items)
    context['total'] = sum(item.total_value for item in items)
    context['received'] = sum(item.total_paid for item in items)

    if context['received'] < context['total']:
        context['is_in_the_red'] = True
    else:
        context['is_in_the_red'] = False

    return render(request, 'client/list_items.html', context)

estofadora/client/templates/client/add.html
{% extends "base.html" %}

{% block title %}Clientes{% endblock title %}

{% block content-header-title %}
Cadastrar cliente
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Cadastrar novo cliente</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li><a href="{% url 'client:list' %}">Clientes</a></li>
<li class="active">Cadastrar</li>
{% endblock content-header-breadcrumb %}

{% block content %}
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
			  <h3 class="box-title">Novo cliente</h3>
			</div>
			<!-- /.box-header -->
			<form role="form" method="POST">
			  <div class="box-body" style="display: block;">
						{% csrf_token %}
		  	    {{ form.non_field_errors}}

				    {% for field in form %}
					    <div class="form-group">
						    {{ field.label_tag }}
						    {{ field }}
						    {{ field.errors }}
					    </div>
				    {% endfor %}
			  </div>
			  <!-- /.box-body -->
			  <div class="box-footer">
			    <button type="submit" class="btn btn-primary">
			    	<i class="fa fa-plus-circle"></i> Submit
			    </button>
			  	<a class="btn btn-default pull-right" href="{% url 'client:list'%}" role="button">
						<i class="fa fa-minus-circle"></i> Cancelar
					</a>
			  </div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

estofadora/client/templates/client/edit.html
{% extends "base.html" %}

{% block title %}Editar {{ client.name }}{% endblock title %}

{% block content-header-title %}
Editar
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Editar cliente</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li><a href="{% url 'client:list' %}">Clientes</a></li>
<li class="active">Editar</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
			  <h3 class="box-title">Editando: {{ client.name }}</h3>
			</div>
			<a class="btn btn-danger btn-remove pull-right"e href="{% url 'client:delete' client.pk %}" role="button">
				<i class="fa fa-trash"></i>
				Remover
			</a>
			<!-- /.box-header -->
			<form  method="POST" enctype="multipart/form-data" role="form">
			  <div class="box-body" style="display: block;">
						{% csrf_token %}
		  	    {{ form.non_field_errors}}

				    {% for field in form %}
					    <div class="form-group">
						    {{ field.label_tag }}
						    {{ field }}
						    {{ field.errors }}
					    </div>
				    {% endfor %}
			  </div>
			  <!-- /.box-body -->
			  <div class="box-footer">
			    <button type="submit" class="btn btn-primary">
			    	<i class="fa fa-plus-circle"></i> Salvar
			    </button>
			  	<a class="btn btn-default pull-right" href="{% url 'client:list'%}" role="button">
						<i class="fa fa-minus-circle"></i> Cancelar
					</a>
			  </div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

estofadora/client/templates/client/list.html
{% extends "base.html" %}

{% block title %}Clientes{% endblock title %}

{% block content-header-title %}
Clientes
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Meus clientes</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li class="active">Clientes</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
	<div class="col-xs-12">
		  <div class="box box-primary">
		    <div class="box-header">
		      <h3 class="box-title">Meus clientes</h3>
		    </div>
		    <!-- /.box-header -->
		    <div class="box-body table-responsive">
		    	<form method="POST" role="form">
	      		{% csrf_token %}
		        <div class="form-inline">
		          <input type="text" name="name" class="form-control" placeholder="Nome da conta">
	            <span>
		            <button type="submit" name="search" class="btn btn-default form-control">
		            	<i class="fa fa-search"></i>
			          </button>
	            </span>
		        </div>
	        </form>
		      <table class="table table-hover">
		      {% if clients %}
		        <thead>
			        <tr>
			          <th>#</th>
			          <th>Nome</th>
			          <th>Email</th>
			          <th>Telefone 1</th>
								<td>Editar</td>
								<td>Itens</td>
			        </tr>
			      </thead>
			      <tbody>
			      	{% for client in clients %}	
				        <tr>
				          <td>{{forloop.counter}}</td>
				          <td>{{client.name}}</td>
				          <td>{{client.email}}</td>
									<td>{{client.telephone1}}</td>
									<th>
										<a href="{% url 'client:edit' client.pk %}"><i class="fa fa-pencil"></i></a>
									</th>
									<th>
										<a href="{% url 'client:list_items' client.pk %}"><i class="fa fa-list"></i></a>
									</th>
				        </tr>
				       {% endfor %}
		        </tbody>
		      {% else %}
				  	<div class="alert alert-warning text-center" role="alert">Nenhum cliente encontrado.</div>
					{% endif %}
		       </table>
		    </div>
		    <!-- /.box-body -->
		  </div>
	  <!-- /.box -->
	</div>
</div>
{% endblock %}

estofadora/client/templates/client/list_items.html
{% extends "base.html" %}

{% block title %}Itens{% endblock title %}

{% block content-header-title %}
Itens
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Listagem de itens</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li><a href="{% url 'client:list' %}">Clientes</a></li>
<li><a href="{% url 'client:edit' client.pk %}">{{ client.name }}</a></li>
<li class="active">Itens</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Meus clientes</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        {% if items %}
          <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Data chegada</th>
                    <th>Data entrega</th>
                    <th>Valor pago/total</th>
                    <td>Detalhes / Editar</td>
                    <td>Fotos</td>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    <tr>
                        <td>{{item.name}}</td>
                        <td>{{item.arrived_date}}</td>
                        <td>{{item.delivery_date }}</td>
                        <td>{{item.total_paid }} / {{item.total_value}}</td>
                        <th><p class="text-center"><a href="{% url 'item:edit' item.pk %}"><i class="fa fa-pencil"></a></i></p></th>
                        <th><a href="{% url 'item:image_list' item.pk %}"><i class="fa fa-picture-o"></a></i></th>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
          <div class="amount">
          	<p class="text-center">
          		Quantidade: {{ amount }}
          	</p> 
          </div>
        {% else %}
          <div class="alert alert-warning text-center" role="alert">
            Nenhum item cadastrado para {{client.name}}.
          </div>
        {% endif %}
      </div>
    </div>
    {% if items %}
      <div class="total_value">
      	<p class="text-right text-primary">
      	Valor total: R$ {{ total }}
      	</p>
      </div>

    	<div class="total_paid">
    		{% if is_in_the_red %}
    		<p class="text-right text-danger">
    		{% else %}	
    		<p class="text-right text-success">
    		{% endif %}
    		Valor recebido: R$ {{ received }}
    		</p>
    	</div>
    {% endif %}
    <a class="btn btn-default" role="button" 
        href="{% url 'client:list' %}">
        <i class="fa fa-arrow-circle-left"></i> Voltar 
    </a>
  </div>
</div>
{% endblock %}