estofadora/client/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.client.views',
    url(r'^(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^listar/$', 'list', name='list'),
    url(r'^(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^(?P<pk>\d+)/itens/', 'list_items', name='list_items'),
    url(r'^$', 'add', name='add'),
)

estofadora/item/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.item.views',
    url(r'^(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^listar/$', 'list', name='list'),
    url(r'^(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^(?P<pk>\d+)/imagens/', 'image_list', name='image_list'),
    url(r'^imagens/(?P<pk>\d+)/remover/', 'image_delete', name='image_delete'),
    url(r'^$', 'add', name='add'),
)

estofadora/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'estofadora.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^cliente/', include('estofadora.client.urls', namespace='client')),
    url(r'^item/', include('estofadora.item.urls', namespace='item')),
    url(r'^login/', include('estofadora.login.urls', namespace='login')),
    url(
        r'^relatorios/',
        include('estofadora.statement.urls', namespace='statement')
    ),
    url(r'^conta/', include('estofadora.bills.urls', namespace='bills')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('estofadora.core.urls', namespace='core')),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

estofadora/item/models.py
import os

from django.db import models
from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver

from estofadora.client.models import Client


class Item(models.Model):

    client = models.ForeignKey(
        Client, related_name='client'
    )

    name = models.CharField('Nome', max_length=256)
    description = models.TextField('')
    concluded = models.BooleanField('Concluido', default=False)
    arrived_date = models.DateTimeField('Chegou', auto_now_add=True)
    delivery_date = models.DateTimeField('Entrega')
    total_value = models.DecimalField(
        'Valor total', max_digits=20, decimal_places=2, default=0.0
    )
    total_paid = models.DecimalField(
        'Valor pago', max_digits=20, decimal_places=2, default=0.0
    )

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Itens'

    def rest_value(self):
        return (float(self.total_value) - float(self.total_paid))

    def all_public_images(self):
        return self.pictures.filter(public=True)

    def __str__(self):
        return self.name


def image_path(data, filename):
    "Returns the filepath where the image is store"
    extension = data.image.path[data.image.path.find('.'):]
    return os.path.join(
        'items/images/{0}/{0}{1}'.format(data.item.name, extension)
    )


class Picture(models.Model):
    AFTER = 'after'
    BEFORE = 'before'
    STATE_CHOICES = (
        (AFTER, 'Depois'),
        (BEFORE, 'Antes'),
    )

    item = models.ForeignKey(
        Item, related_name='pictures'
    )
    created_at = models.DateField('Criado em', auto_now_add=True)
    public = models.BooleanField('Publico', default=False)
    state = models.CharField(
        'Estado', max_length=6, choices=STATE_CHOICES, default=BEFORE
    )
    image = models.ImageField(
        upload_to=image_path, verbose_name="Imagem",

    )

    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'

    def __str__(self):
        return '{0} - {1}'.format(self.item.name, self.created_at.isoformat())


# Delete the file associated with the model instance
@receiver(post_delete, sender=Picture)
def mymodel_delete(sender, instance, **kwargs):
    if instance.image:
        instance.image.delete(False)

estofadora/item/forms.py
# coding: utf-8
from django import forms

from multiupload.fields import MultiFileField

from estofadora.client.models import Client

from .models import Item, Picture


class ItemForm(forms.ModelForm):
    client = forms.ModelChoiceField(
        queryset=Client.objects.all(), label="Cliente")
    description = forms.CharField(label="Descrição", widget=forms.Textarea)

    class Meta:
        model = Item
        fields = [
            'client', 'name', 'delivery_date',
            'total_value', 'total_paid', 'description', 'concluded'
        ]

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['client'].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update(
            {'class': 'form-control'}
        )
        self.fields['delivery_date'].widget.attrs.update(
            {'class': 'form-control'}
        )
        self.fields['total_value'].widget.attrs.update(
            {'class': 'form-control'}
        )
        self.fields['total_paid'].widget.attrs.update(
            {'class': 'form-control'}
        )


class ItemPictureForm(ItemForm):

    files = MultiFileField(
        label="Imagens", min_num=0, max_num=10,
        max_file_size=(1024 * 1024 * 5), required=False
    )

    def save(self, commit=True):
        instance = super(ItemPictureForm, self).save(commit)

        for each in self.cleaned_data['files']:
            Picture.objects.create(image=each, item=instance)

        return instance


class PictureForm(forms.Form):

    files = MultiFileField(
        label="Imagens", min_num=0, max_num=10, max_file_size=(1024 * 1024 * 5)
    )

    def save(self, instance, commit=True):

        for each in self.cleaned_data['files']:
            Picture.objects.create(image=each, item=instance)

estofadora/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import ItemForm, ItemPictureForm, PictureForm
from .models import Item, Picture


@login_required
def add(request):
    context = {}

    if request.method == 'POST':
        item_picture_form = ItemPictureForm(request.POST, request.FILES)

        if item_picture_form.is_valid():
            item_picture_form.save()

            messages.success(request, 'Item cadastrado com sucesso!')
            item_picture_form = ItemPictureForm()

    else:
        item_picture_form = ItemPictureForm()

    context['item_picture_form'] = item_picture_form
    context['section'] = 'item_add'
    return render(request, 'item/add.html', context)


@login_required
def edit(request, pk):
    context = {}
    item = get_object_or_404(Item, pk=pk)

    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)

        if form.is_valid():
            form.save()
            messages.success(request, 'Item alterado com sucesso!')
            return redirect(
                reverse('client:list_items', args=[item.client.pk])
            )
    else:
        form = ItemForm(instance=item)

    context['form'] = form
    context['item'] = item
    return render(request, 'item/edit.html', context)


@login_required
def list(request):
    context = {}

    if request.method == 'POST':
        item_name = request.POST.get('name')
        items = Item.objects.filter(name__icontains=item_name)

    else:
        items = Item.objects.all()

    context['items'] = items
    context['section'] = 'items'
    return render(request, 'item/list.html', context)


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    messages.success(request, 'Item removido com sucesso!')

    return redirect(reverse('item:list'))


@login_required
def image_list(request, pk):
    context = {}
    item = get_object_or_404(Item, pk=pk)

    pictures = Picture.objects.filter(item=item)

    if request.method == 'POST':

        # Form to add a new image
        if 'add-form' in request.POST:
            picture_form = PictureForm(request.POST, request.FILES)

            if picture_form.is_valid():
                picture_form.save(instance=item, commit=False)
                messages.success(request, 'Imagem enviada com sucesso!')
                return redirect(reverse('item:image_list', args=[item.pk]))

        # Form to change image's state
        else:
            checked_ids = request.POST.getlist('checks[]')
            selected_states = request.POST.getlist('selects[]')

            # Create a list because will be needed to remove the checked itens.
            all_pictures = [p for p in pictures]

            all_pictures = removeCheckedPictureFromAllPictures(
                checked_ids, all_pictures
            )

            setFalseInRemainPictures(all_pictures)

            setTrueInCheckedPictures(checked_ids)

            if selected_states:
                for selected in selected_states:
                    _id, state = tuple(selected.split('_'))

                    picture = get_object_or_404(Picture, pk=_id)
                    picture.state = state
                    picture.save()

            messages.success(request, 'Alterado com sucesso!')
            return redirect(reverse('item:image_list', args=[item.pk]))

    context['item'] = item
    context['pictures'] = pictures
    context['picture_form'] = PictureForm()
    return render(request, 'item/list_images.html', context)


def removeCheckedPictureFromAllPictures(checked_ids, all_pictures):
    for picture in all_pictures:
        for check in checked_ids:
            if int(picture.pk) == int(check):
                all_pictures.remove(picture)
    return all_pictures


def setFalseInRemainPictures(all_pictures):
    for picture in all_pictures:
        picture.public = False
        picture.save()


def setTrueInCheckedPictures(checked_ids):
    for check in checked_ids:
        picture = get_object_or_404(Picture, pk=check)
        picture.public = True
        picture.save()


@login_required
def image_delete(request, pk):
    picture = get_object_or_404(Picture, pk=pk)
    item = picture.item
    picture.delete()
    messages.success(request, 'Imagem removida com sucesso!')

    return redirect(reverse('item:image_list', args=[item.pk]))

estofadora/item/templates/item/add.html
{% extends "base.html" %}

{% block extra_js %}
<script>
    $('.picture-formset').formset({
        addText: 'Adicionar imagem',
        deleteText: 'Remover'
    });
</script>
{% endblock %}

{% block title %}Cadastrar peça{% endblock title %}

{% block content-header-title %}
Cadastrar peça
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Exemplo: Sofa, poltrona, cadeira ...</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li><a href="{% url 'item:list' %}">Peças</a></li>
<li class="active">Cadastrar</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Nova conta</h3>
      </div>
      <!-- /.box-header -->
      <form enctype="multipart/form-data" method="post" role="form">
        <div class="box-body" style="display: block;">
          {% csrf_token %}
          {{item_picture_form.as_p}}
        </div>
        <div class="box-footer">
          <button class="btn btn-primary" 
            type="submit" name="post_form">
            <i class="fa fa-plus-circle"></i>
            Cadastrar
          </button>
        </div>
      </form>
      </div>
      <!-- /.box-body -->
    </div>
  </div>
</div>

{% endblock %}

estofadora/item/templates/item/edit.html
{% extends "base.html" %}

{% block title %}Editar {{ client.name }}{% endblock title %}

{% block content-header-title %}
Editar
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Editar peça</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li><a href="{% url 'item:list' %}">Peças</a></li>
<li class="active">Editar</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
			  <h3 class="box-title">Editando: {{ item.name }}</h3>
			</div>
			<a class="btn btn-danger btn-remove pull-right"e href="{% url 'item:delete' item.pk %}" role="button">
				<i class="fa fa-trash"></i>
				Remover
			</a>
			<!-- /.box-header -->
			<form  method="POST" enctype="multipart/form-data" role="form">
			  <div class="box-body" style="display: block;">
						{% csrf_token %}
		  	    {{ form.non_field_errors}}

				    {% for field in form %}
					    <div class="form-group">
						    {{ field.label_tag }}
						    {{ field }}
						    {{ field.errors }}
					    </div>
				    {% endfor %}
			  </div>
			  <!-- /.box-body -->
			  <div class="box-footer">
			    <button type="submit" class="btn btn-primary">
			    	<i class="fa fa-plus-circle"></i> Salvar
			    </button>
			  	<a class="btn btn-default pull-right" href="{% url 'item:list'%}" role="button">
						<i class="fa fa-minus-circle"></i> Cancelar
					</a>
			  </div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

estofadora/item/templates/item/list.html
{% extends "base.html" %}

{% block title %}Clientes{% endblock title %}

{% block content-header-title %}
Peças
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Todas as peças</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li class="active">Peças</li>
<li class="active">Listar todas</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Todas as peças</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <form method="POST" role="form">
          {% csrf_token %}
          <div class="form-inline">
            <input type="text" name="name" class="form-control" placeholder="Nome da conta">
            <span>
              <button type="submit" name="search" class="btn btn-default form-control">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
        <table class="table table-hover">
        {% if items %}
          <thead>
              <tr>
                <th>#</th>
                <th>Cliente</th>
                <th>Peça</th>
                <th>Data chegada</th>
                <th>Data entrega</th>
                <th>Valor pago/total</th>
                <td>Detalhes/Editar</td>
                <td>Fotos</td>
              </tr>
            </thead>
            <tbody>
              {% for item in items %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{item.client.name}}</td>
                  <td>{{item.name}}</td>
                  <td>{{item.arrived_date|date:"D d/m/Y"}}</td>
                  <td>{{item.delivery_date|date:"D d/m/Y" }}</td>
                  <td>{{item.total_paid }} / {{item.total_value}}</td>
                  <th>
                    <p class="text-center">
                      <a href="{% url 'item:edit' item.pk %}"><i class="fa fa-pencil"></i></a>
                    </p>
                  </th>
                  <th>
                    <p class="text-center">
                      <a href="{% url 'item:image_list' item.pk %}"><i class="fa fa-picture-o"></i></a>
                    </p>
                  </th>
                </tr>
              {% endfor %}
            </tbody>
        {% else %}
          <div class="alert alert-warning text-center" role="alert">Nenhum item encontrado.</div>
        {% endif %}
         </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>
{% endblock %}

estofadora/item/templates/item/list_images.html
{% extends "base.html" %}
{% block extra_js %}
<script>
    $('.picture-formset').formset({
        addText: 'Adicionar imagem',
        deleteText: 'Remover'
    });
</script>
{% endblock %}

{% block title %}Imagens{% endblock title %}

{% block content-header-title %}
Imagens
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Listagem de imagens</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li>Itens</li>
<li><a href="{% url 'item:edit' item.pk %}">{{ item.name }}</a></li>
<li class="active">Imagens</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Enviar nova imagem</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
        <!-- /.box-tools -->
      </div>
      <!-- /.box-header -->
      <div class="box-body" style="display: block;">
        <form enctype="multipart/form-data" method="post" role="form">
          {% csrf_token %}
          {{picture_form.as_p}}
          <div>
            <button class="btn btn-primary" 
                type="submit" name="add-form">
                <i class="fa fa-paper-plane"></i>
                Enviar
            </button>
          </div>
        </form>    
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Imagens de {{ item }} <small>{{ item.client.name }}</small></h3>
      </div>
      <!-- /.box-header -->
      <form method="POST">
        <div class="box-body table-responsive">
          {% if pictures %}
            {% csrf_token %}
            <div class="row">
              {% for picture in pictures %}
                <div class="col-lg-3 col-md-4 col-xs-12 portfolio-item">
                  <a target="_blank" href="{{picture.image.url}}">
                    <img src="{{picture.image.url}}" class="img-responsive img-thumbnail item-image {% if picture.public %}public-image{%endif%}"
                    {% if picture.public %}
                        title="Imagem publica"
                    {% else %} 
                        title="Imagem privada"
                    {% endif %}>
                  </a>
                  <a class="btn btn-danger btn-xs" role="button" 
                      href="{% url 'item:image_delete' picture.pk %}">Apagar 
                  </a>
                  <select name="selects[]" title="Estado do trabalho">
                    <option value="{{picture.id}}_before"
                        {% if picture.state == 'before'%} selected {% endif%}>Antes
                    </option>
                    <option value="{{picture.id}}_after"
                      {% if picture.state == 'after'%} selected {% endif%}>Depois
                    </option>
                  </select>
                  <input name="checks[]"
                    type="checkbox"
                    title="Deixar imagem publica"
                    {% if picture.public %}
                        checked
                    {% endif %}
                    value="{{picture.id}}">
                </div>
              {% endfor %}
            </div>
          {% else %}
          <div class="alert alert-warning text-center" role="alert">Nenhuma imagem adicionada!</div>
          {% endif %}
        </div>
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-floppy-o"></i>
              Alterar
            </button>
        </div>
      </form>
    </div>
  	<a class="btn btn-default" role="button" 
  		href="{% url 'client:list_items' item.client.pk %}">
      <i class="fa fa-arrow-circle-left"></i> Voltar 
  	</a>
  </div>
</div>

{% endblock %}