estofadora/bills/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.bills.views',
    url(r'^listar/$', 'list', name='list'),
    url(r'^(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^(?P<pk>\d+)/pago/', 'mark_as_paid', name='mark_as_paid'),
    url(r'^$', 'new', name='new'),
)

estofadora/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.core.views',
    url(r'^$', 'site', name='site'),
    url(r'^inicio/$', 'home', name='home'),
    url(r'^portfolio/$', 'portfolio', name='portfolio'),
    url(r'^contato/$', 'contact', name='contact'),

    url(r'^mensagens/$', 'contactMessages', name='contactMessages'),
    url(r'^(?P<pk>\d+)/remover/', 'deleteMessage', name='deleteMessage'),
    url(r'^(?P<pk>\d+)/lida/', 'markMessageAsRead', name='markMessageAsRead'),
)

estofadora/item/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.item.views',
    url(r'^(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^listar/$', 'list', name='list'),
    url(r'^(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^(?P<pk>\d+)/imagens/', 'image_list', name='image_list'),
    url(r'^imagens/(?P<pk>\d+)/remover/', 'image_delete', name='image_delete'),
    url(r'^$', 'add', name='add'),
)

estofadora/login/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^sair/$', 'django.contrib.auth.views.logout',
        {'next_page': 'login:login'}, name='logout'),
    url(r'^$', 'estofadora.login.views.login', name='login'),
)

estofadora/statement/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.statement.views',
    url(r'^caixa/$', 'cash', name='cash'),
    url(r'^caixa-mensal/$', 'cash_month', name='cash_month'),
    url(r'^caixa-anual/$', 'cash_annual', name='cash_annual'),
    url(r'^caixa/(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^caixa/(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^$', 'home', name='home'),
)

estofadora/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'estofadora.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^cliente/', include('estofadora.client.urls', namespace='client')),
    url(r'^item/', include('estofadora.item.urls', namespace='item')),
    url(r'^login/', include('estofadora.login.urls', namespace='login')),
    url(
        r'^relatorios/',
        include('estofadora.statement.urls', namespace='statement')
    ),
    url(r'^conta/', include('estofadora.bills.urls', namespace='bills')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('estofadora.core.urls', namespace='core')),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

estofadora/core/models.py
from django.db import models


class Contact(models.Model):

    name = models.CharField('Nome', max_length=200)
    email = models.CharField('Email', max_length=200, null=True, blank=True)
    telephone = models.CharField(
        'Telefone', max_length=15, null=True, blank=True
    )
    subject = models.CharField(
        'Assunto', max_length=30
    )
    description = models.TextField('Mensagem')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    read = models.BooleanField('Lido', default=False)

    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

    def __str__(self):
        return '{0} - {1}'.format(self.name, self.email)

estofadora/core/forms.py
# conding: utf-8
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['name', 'email', 'telephone', 'subject', 'description']

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()

        email = cleaned_data.get('email')
        telephone = cleaned_data.get('telephone')

        if not email and not telephone:
            raise forms.ValidationError(
                'Por favor, entre com pelo menos uma opção de contato. Email ou telefone.'
            )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Nome completo'}
        )
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Seu email'}
        )
        self.fields['telephone'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Seu telefone com DDD'}
        )
        self.fields['subject'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Assunto da mensagem'}
        )
        self.fields['description'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Sua mensagem'}
        )

estofadora/core/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from estofadora.item.models import Item, Picture
from estofadora.bills.models import Bill

from .forms import ContactForm
from .models import Contact


@login_required
def home(request):
    context = {}

    # Every week has a number, get the atual number.
    this_week = datetime.datetime.now().isocalendar()[1]

    # Get all items and separate them which the week number matchs
    items = Item.objects.all().order_by('-delivery_date')

    items_to_delivery = [
        i for i in items if i.delivery_date.isocalendar()[1] == this_week
    ]

    # Gell all bills and separate them which the week number matchs
    bills = Bill.objects.all().order_by('-date_to_pay')

    week_bills = [
        b for b in bills if b.date_to_pay.isocalendar()[1] == this_week
    ]

    context['items'] = items_to_delivery
    context['bills'] = week_bills
    context['section'] = 'home'
    return render(request, 'index.html', context)


def site(request):
    context = {}

    pictures = Picture.objects.filter(
        public=True, state='after').order_by('-created_at')[:4]
    context['pictures'] = pictures
    return render(request, 'site/site_index.html', context)


def portfolio(request):
    context = {}
    items = Item.objects.all()

    context['items'] = items
    return render(request, 'site/portfolio.html', context)


def contact(request):
    context = {}

    if request.method == 'POST':

        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(
                request, 'Obrigado pela mensagem, entraremos em contato!'
            )
            return redirect(reverse('core:contact'))
    else:
        form = ContactForm()

    context['form'] = form
    return render(request, 'site/contact.html', context)


@login_required
def contactMessages(request):
    context = {}

    contactMessages = Contact.objects.all().order_by('-created_at')

    context['contactMessages'] = contactMessages
    context['section'] = 'messages'
    return render(request, 'contactMessages.html', context)


@login_required
def deleteMessage(request, pk):
    contact = get_object_or_404(Contact, pk=pk)

    contact.delete()

    messages.success(request, 'Mensagem removida com sucesso!')
    return redirect(reverse('core:contactMessages'))


@login_required
def markMessageAsRead(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    contact.read = True
    contact.save()

    messages.success(request, 'Mensagem lida!')
    return redirect(reverse('core:contactMessages'))

estofadora/core/templates/base.html
{% load staticfiles %}
{% load contactMesssages_tag%}
<!DOCTYPE html>
<!-- Copyright &copy; 2014-2016 http://almsaeedstudio.com Almsaeed Studio -->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock title %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "css/AdminLTE.min.css" %}">
  <link rel="stylesheet" href="{% static "css/skin-blue-light.min.css" %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "css/font-awesome/css/font-awesome.min.css" %}">
  <!-- Custom style -->
  <link rel="stylesheet" href="{% static "css/main.css" %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini fixed">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>E</b>AP</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Ana</b>Paula</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li>
            <a href="{% url 'core:contactMessages' %}">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">{% get_mensagens %}</span>
            </a>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
              <span class="hidden-xs">{{ user.first_name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">-->
                <p>
                  {{ user.first_name }}
                  <small><strong>Último acesso:</strong> {{ user.last_login}} </small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  {# <a href="#" class="btn btn-default btn-flat">Perfil</a> #}
                </div>
                <div class="pull-right">
                  <a href="{% url 'login:logout' %}" class="btn btn-default btn-flat">Sair</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li {% if section == "home" %}class="active"{% endif %}>
          <a href="{%url 'core:home' %}"><i class="fa fa-home"></i> <span>Início</span></a><
        /li>
        <li class="header">CADASTRAR</li>
        <li {% if section == "client_add" %}class="active"{% endif %}>
          <a href="{% url 'client:add' %}"><i class="fa fa-user"></i> <span>Cliente</span></a>
        </li>
        <li {% if section == "item_add" %}class="active"{% endif %}>
          <a href="{% url 'item:add' %}"><i class="fa fa-cube"></i> <span>Peça</span></a>
        </li>
        <li {% if section == "bill_new" %}class="active"{% endif %}>
          <a href="{% url 'bills:new' %}"><i class="fa fa-money"></i> <span>Conta</span></a>
        </li>
        <li class="header">LISTAR</li>
        <li {% if section == "clients" %}class="active"{% endif %}>
          <a href="{% url 'client:list' %}"><i class="fa fa-users"></i> <span>Clientes</span></a>
        </li>
        <li {% if section == "items" %}class="active"{% endif %}>
          <a href="{% url 'item:list' %}"><i class="fa fa-cubes"></i> <span>Peças</span></a>
        </li>
        <li {% if section == "bills" %}class="active"{% endif %}>
          <a href="{% url 'bills:list' %}"><i class="fa fa-money"></i> <span>Contas</span></a>
        </li>
        <li class="header">RELATÓRIOS</li>
        <li {% if section == "cash" %}class="active"{% endif %}>
          <a href="{% url 'statement:cash' %}"><i class="fa fa-line-chart"></i> <span>Caixa diário</span></a>
        </li>
        <li {% if section == "cash_month" %}class="active"{% endif %}>
          <a href="{% url 'statement:cash_month' %}"><i class="fa fa-bar-chart"></i> <span>Caixa mensal</span></a>
        </li>
        <li {% if section == "cash_annual" %}class="active"{% endif %}>
          <a href="{% url 'statement:cash_annual' %} "><i class="fa fa-area-chart"></i> <span>Caixa anual</span></a>
        </li>
        <li class="header">ATALHOS</li>
        <li {% if section == "messages" %}class="active"{% endif %}>
          <a href="{%url 'core:contactMessages' %}">
            <i class="fa fa-envelope-o"></i> <span>Mensages</span>
          </a>
        </li>
        <li><a href="{%url 'core:site' %}"><i class="fa fa-external-link"></i> <span>Site</span></a></li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block content-header-title %}
        {% endblock content-header-title %}
        
        {% block content-header-subtitle %}
        {% endblock content-header-subtitle %}
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'core:home' %}"><i class="fa fa-home"></i> Home</a></li>
        {% block content-header-breadcrumb %}
        {% endblock content-header-breadcrumb %}
      </ol>
    </section>
    <!-- Alert messages -->
    <section>
      {% if messages %}
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <div class="alert alert-success">
                <i class="fa fa-check"></i>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{message}}
            </div>
          {% elif message.tags == 'warning'%}
            <div class="alert alert-warning">
                <i class="fa fa-warning"></i>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{message}}
            </div>
          {% elif message.tags == 'error'%}
            <div class="alert alert-danger">
                <i class="fa fa-ban"></i>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{message}}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    </section>
    <!-- /.messages -->

    <!-- Main content -->
    <section class="content">
      {% block content %}
      {% endblock content %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <strong>Hoje:</strong> {% now "j F Y" %}
    </div>
    <strong>Estofadora Ana Paula</strong>
  </footer>

</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.4 -->
<script src="{% static "js/jquery.min.js" %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static "js/bootstrap.min.js" %}"></script>
<!-- Slimscroll -->
<script src="{% static "js/jquery.slimscroll.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "js/app.min.js" %}"></script>

{% block extra_js %} 
{% endblock extra_js %}
</body>
</html>

estofadora/core/templates/base_old.html
{% load staticfiles %}
{% load contactMesssages_tag%}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <!-- <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}" />   -->
    <link rel="stylesheet" href="{% static "font-awesome-4.6.1/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>
    <!--[if lte IE 8]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
      <![endif]-->

      <!-- Add your site or application content here -->
      <div class="header">
          <div class="navbar navbar-default" role="navigation">
            <div class="container">
              <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#js-navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>

              <a class="navbar-brand" href="{% url 'core:site' %}">estofadora</a>
          </div>

          <div class="collapse navbar-collapse" id="js-navbar-collapse">

            <ul class="nav navbar-nav">
              <li>
                <a href="{% url 'core:home' %}"><i class="fa fa-home"></i></a>
              </li>
              <li>
                <a href="{% url 'client:list' %}"><i class="fa fa-users"></i>Clientes</a>
              </li>
              <li class="dropdown">
                <a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="{% url 'statement:home' %}">
                  <i class="fa fa-plus-circle"></i> Cadastrar 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'item:add' %}">Item</a>
                    <a href="{% url 'bills:new' %}">Conta</a>
                  </li>
                </ul>
              </li>
              <li class="dropdown">
                <a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="{% url 'statement:home' %}">
                  <i class="fa fa-bar-chart"></i> Relatórios 
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'statement:cash' %}">Caixa diário</a>
                    <a href="{% url 'statement:cash_month' %}">Caixa mensal</a>
                    <a href="{% url 'statement:cash_annual' %}">Caixa anual</a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="{% url 'core:contactMessages' %}"><span class="badge">{% get_mensagens %}</span> Mensagens </a> 
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="{% url 'login:logout' %}">
                <i class="fa fa-sign-out"></i>Sair
              </a>
            </li>
          </ul>
      </div>
  </div>
</div>
</div>

<div class="container">
    {% if messages %}
        {% for message in messages %}
	        {% if message.tags == 'success' %}
		        <div class="alert alert-success mesagem">
		            <i class="fa fa-check"></i>
		            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		            {{message}}
		        </div>
	        {% elif message.tags == 'warning'%}
		        <div class="alert alert-warning mesagem">
		            <i class="fa fa-warning"></i>
		            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		            {{message}}
		        </div>
	        {% elif message.tags == 'error'%}
		        <div class="alert alert-danger mesagem">
		            <i class="fa fa-ban"></i>
		            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		            {{message}}
		        </div>
	        {% endif %}
        {% endfor %}
    {% endif %}

	{% block content %}
	{% endblock %}
</div>

<div class="footer">
  <div class="container">
    <p><span class=""></span> Estofadora Ana Paula </p>
</div>
</div>


<!-- Google Analytics: change UA-XXXXX-X to be your site's ID -->
<script>
 /*!function(A,n,g,u,l,a,r){A.GoogleAnalyticsObject=l,A[l]=A[l]||function(){
     (A[l].q=A[l].q||[]).push(arguments)},A[l].l=+new Date,a=n.createElement(g),
     r=n.getElementsByTagName(g)[0],a.src=u,r.parentNode.insertBefore(a,r)
 }(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-XXXXX-X');
 ga('send', 'pageview');*/
</script>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.formset.js" %}"></script>
{% block extra_js %} 
{% endblock %}
</body>
</html>

estofadora/core/templates/index_old.html
{% extends "base.html" %}
{% load quantity_tags%}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head text-center">
                    Área administrativa
                </h1>
                <h2 class="splash-subhead text-center">
                    <small> Gerencie clientes, itens, contas e relatórios.</small>
                </h2>
            </div>
        </div>
    </div>
</div>
<br>

<div class="row">
    <div class="col-lg-3">
        <a href="{% url 'client:list' %}">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{% get_clients %}</p>
                            <p class="announcement-text"> Clientes</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    
    <div class="col-lg-3">
        <a href="{% url 'item:list' %}">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-cubes fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">{% get_items %}</p>
                    <p class="announcement-text"> Itens</p>
                  </div>
                </div>
              </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3">
        <a href="">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <i class="fa fa-file-image-o fa-5x"></i>
                        </div>
                        <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{% get_pictures %}</p>
                            <p class="announcement-text"> Imagens</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3">
        <a href="{% url 'bills:list' %}">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <i class="fa fa-money fa-5x"></i>
                        </div>
                        <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{% get_bills %}</p>
                            <p class="announcement-text"> Contas</p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div> <!-- #row -->

<div class="well well-sm">
    <p class="text-center">
       <i class="fa fa-calendar"></i> Data de hoje: {% now "j F Y" %}
    </p>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
        <i class="fa fa-truck"></i> Entregas da semana</h3>
    </div>
    <div class="panel-body">
        {% if items %}
            

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Cliente</th>
                        <th>Item</th>
                        <th>Data de entrega</th>
                        <th>Estado</th>
                        <td>Detalhes</td>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}   
                        <tr>
                            <td>{{item.client.name}}</td>
                            <td>{{item.name}}</td>
                            <td>{{item.delivery_date}}</td>
                            {% if item.concluded %}
                                <td><span class="label label-success">Entregue</span></td>
                            {% else %}
                                <td><span class="label label-danger">Pendente</span></td>
                            {% endif %}
                            <th><p class="text-center"><a href="{% url 'item:edit' item.pk %}"><i class="fa fa-info-circle fa-2x"></i></a></p>
                            </th>
                        </tr>
                        
                    {% endfor %}
                </tbody>
            </table>
        
        {% else %}
            <div class="alert alert-warning" role="alert">
                <p>Nenhuma entrega para essa semana.</p>
            </div>   
        {% endif %}
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
        <i class="fa fa-dollar"></i> Contas da semana</h3>
    </div>
    <div class="panel-body">
        {% if bills %}
            

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Valor</th>
                        <th>Data de pagamento</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bill in bills %}   
                        <tr>
                            <td>{{bill.name}}</td>
                            <td>{{bill.value}}</td>
                            <td>{{bill.date_to_pay}}</td>
                            {% if bill.is_paid %}
                                <td><span class="label label-success">Pago</span></td>
                            {% else %}
                                <td><span class="label label-danger">Pendente</span></td>
                            {% endif %}
                        </tr>
                        
                    {% endfor %}
                </tbody>
            </table>
        
        {% else %}
            <div class="alert alert-warning" role="alert">
                <p>Nenhuma conta para essa semana.</p>
            </div>   
        {% endif %}
    </div>
</div>

{% endblock %}