estofadora/statement/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'estofadora.statement.views',
    url(r'^caixa/$', 'cash', name='cash'),
    url(r'^caixa-mensal/$', 'cash_month', name='cash_month'),
    url(r'^caixa-anual/$', 'cash_annual', name='cash_annual'),
    url(r'^caixa/(?P<pk>\d+)/remover/', 'delete', name='delete'),
    url(r'^caixa/(?P<pk>\d+)/editar/', 'edit', name='edit'),
    url(r'^$', 'home', name='home'),
)

estofadora/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'estofadora.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^cliente/', include('estofadora.client.urls', namespace='client')),
    url(r'^item/', include('estofadora.item.urls', namespace='item')),
    url(r'^login/', include('estofadora.login.urls', namespace='login')),
    url(
        r'^relatorios/',
        include('estofadora.statement.urls', namespace='statement')
    ),
    url(r'^conta/', include('estofadora.bills.urls', namespace='bills')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('estofadora.core.urls', namespace='core')),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

estofadora/statement/models.py
# conding: utf-8
from django.db import models
from django.db import IntegrityError, transaction


class Cash(models.Model):

    date = models.DateField('Dia')
    history = models.CharField('Histórico', max_length=100)
    income = models.DecimalField(
        'Entrada', max_digits=20, decimal_places=2, default=0.0
    )
    expenses = models.DecimalField(
        'Saida', max_digits=20, decimal_places=2, default=0.0
    )

    class Meta:
        ordering = ['date']
        verbose_name = ('Cash')
        verbose_name_plural = ('Cash')

    def save(self, *args, **kwargs):
        # Need instance balance obj to store the total value
        try:
            # If exists will raise IntegrityError.
            with transaction.atomic():
                obj = Balance(date=self.date, value=self.total)
                obj.save()

        except IntegrityError:
            # Get the balance and update
            obj = Balance.objects.get(date=self.date)
            obj.value += self.total
            obj.save()

        # Call the "real" save() method.
        super(Cash, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        '''
            If an item was removed, must reduce its value on
            the total.
        '''
        obj = Balance.objects.get(date=self.date)
        obj.value -= self.total

        if obj.value == float(0):
            obj.delete()
        else:
            obj.save()

        super(Cash, self).delete(*args, **kwargs)

    @property
    def total(self):
        '''
            Total from the instanced object.
        '''
        return self.income - self.expenses

    @staticmethod
    def total_value():
        '''
            Total from all objects.
        '''
        incomes = sum(item.income for item in Cash.objects.all())
        expenses = sum(item.expenses for item in Cash.objects.all())
        return incomes - expenses

    @staticmethod
    def list_years():
        '''
            Returns a list of years that there are objects cash saved.
        '''
        cashs = Cash.objects.all()
        years = [c.date.year for c in cashs]

        dicio = {}
        # Remove the repeated years.
        for year in years:
            dicio[year] = 1

        return list(dicio.keys())

    @staticmethod
    def filter_by_date(day=None, month=None, year=None):
        filters = {
            'date__day': day,
            'date__month': month,
            'date__year': year,
        }
        # Select all values that are not None.
        filter_by = {
            key: value for key, value in filters.items() if value is not None
        }

        return Cash.objects.filter(**filter_by)

    @staticmethod
    def total_value_by_date(day=None, month=None, year=None):
        filters = {
            'date__day': day,
            'date__month': month,
            'date__year': year,
        }
        # Select all values that are not None.
        filter_by = {
            key: value for key, value in filters.items() if value is not None
        }

        incomes = sum(
            item.income for item in Cash.objects.filter(**filter_by)
        )
        expenses = sum(
            item.expenses for item in Cash.objects.filter(**filter_by)
        )
        return incomes - expenses

    @staticmethod
    def create_balance(content, total_before):
        '''
            Returns a list that each item has the total balance value.

            Create a new temporary field (balance) that will save the amount of
            balance of item. Example:

            ITEM  TOTAL  BALANCE
            item0 -1000  -1000    (item0.total + total from the day before)
            item1 +500   -500     (item1.total + item0.balance)
            item2 +600   100      (item2.total + item1.balance)
            etc...
            '''
        last_element = len(content) - 1
        balance = 0

        for index, item in enumerate(content):
            if index == 0:
                # If is the first on, sum the value with the value
                # from the year before.
                item.balance = item.total + total_before
            else:
                item.balance = content[index - 1].balance + (item.total)

            # The last one has the total
            if index == last_element:
                balance = item.balance

        return content, balance


class Balance(models.Model):

    date = models.DateField('Dia', unique=True)
    value = models.DecimalField(
        'Valor', max_digits=20, decimal_places=2, default=0.0
    )

    class Meta:
        ordering = ['date']
        verbose_name = ('Balance')
        verbose_name_plural = ('Balance')

    @staticmethod
    def total_balance_before(date):
        '''
            Returns the total value until the date
            that was given.
        '''
        items = Balance.objects.filter(date__lt=date)

        total = sum(i.value for i in items)

        return total

    @staticmethod
    def balance_from_month(year, month):
        '''
            Returns the total value from the year and month that
            was given.
        '''
        items = Balance.objects.filter(date__year=year, date__month=month)

        total = sum(i.value for i in items)

        return total

estofadora/statement/forms.py
# conding: utf-8
from django import forms
from .models import Cash


class CashForm(forms.ModelForm):

    class Meta:
        model = Cash
        fields = ['date', 'history', 'income', 'expenses']

    def __init__(self, *args, **kwargs):
        super(CashForm, self).__init__(*args, **kwargs)
        self.fields['date'].widget.attrs.update({'class': 'form-control'})
        self.fields['history'].widget.attrs.update({'class': 'form-control'})
        self.fields['income'].widget.attrs.update({'class': 'form-control'})
        self.fields['expenses'].widget.attrs.update({'class': 'form-control'})

estofadora/statement/views.py
from datetime import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages

from estofadora.core.utils import MONTHS, last_day_of, month_before_of

from .forms import CashForm
from .models import Cash, Balance


@login_required
def home(request):
    return render(request, 'statement/statement.html')


@login_required
def cash(request):
    context = {}
    date = datetime.now().date()

    content = Cash.objects.filter(date=date)

    form = CashForm(initial={'date': date})

    if request.method == 'POST':

        if 'search_form' in request.POST:
            date = request.POST.get('search_date')
            # Format the date to 21/12/2015 or 2015-12-21
            try:
                date = datetime.strptime(date, '%d/%m/%Y').date()
            except ValueError:
                date = datetime.strptime(date, '%Y-%m-%d').date()

            content = Cash.objects.filter(date=date)

        else:

            form = CashForm(request.POST)

            if form.is_valid():
                form.save()

                messages.success(request, 'Registrado com sucesso!')

                return redirect(reverse('statement:cash'))

    total_before = Balance.total_balance_before(date)
    content, balance = Cash.create_balance(content, total_before)

    context['form'] = form
    context['content'] = content
    context['total_value'] = balance
    context['total_before'] = total_before
    context['choose_date'] = date
    context['section'] = 'cash'
    return render(request, 'statement/cash.html', context)


@login_required
def delete(request, pk):
    cash = get_object_or_404(Cash, pk=pk)
    cash.delete()
    messages.success(request, 'Registro removido com sucesso!')
    return redirect(reverse('statement:cash'))


@login_required
def edit(request, pk):
    context = {}
    cash = get_object_or_404(Cash, pk=pk)

    if request.method == 'POST':
        form = CashForm(request.POST, instance=cash)
        if form.is_valid():
            form.save()
            return render(
                request, 'statement/item_edit_form_success.html',
                {'item': cash}
            )
        else:
            context['form_error'] = True
    else:
        form = CashForm(instance=cash)

    context['form'] = form
    context['item'] = cash
    return render(request, 'statement/item_edit_form.html', context)


@login_required
def cash_month(request):
    context = {}
    date = datetime.now().date()
    year = date.year
    month = date.month

    # If a date was not given, filter by the atual date.
    content = Cash.filter_by_date(month=month, year=year)
    total_value = Cash.total_value_by_date(month=month, year=year)

    if request.method == 'POST':
        month = int(request.POST.get('selectmonth'))
        year = int(request.POST.get('selectyear'))

        content = Cash.filter_by_date(month=month, year=year)
        total_value = Cash.total_value_by_date(month=month, year=year)

    y, m = month_before_of(year, month)
    last_day_of_month_before = last_day_of(y, m)

    total_before = Balance.total_balance_before(last_day_of_month_before)

    content, total_value = Cash.create_balance(content, total_before)

    context['content'] = content
    context['total_value'] = total_value
    context['total_before'] = total_before
    context['choose_month'] = month
    context['choose_year'] = year
    context['months'] = MONTHS
    context['years'] = Cash.list_years()
    context['section'] = 'cash_month'
    return render(request, 'statement/cash_month.html', context)


@login_required
def cash_annual(request):
    context = {}
    # If an year was not given, use the atual year.
    year = datetime.now().date().year

    if request.method == 'POST':
        year = int(request.POST.get('selectyear'))

    balances = []
    month = 1
    while month < 13:
        # Get the total balance from January to December.
        balance = Balance.balance_from_month(year=year, month=month)
        balances.append(float(balance))
        month += 1

    total_value = Cash.total_value_by_date(year=year)

    # Get the previous year to sum the total of it.
    january = 1
    y, m = month_before_of(year, january)
    last_day_year_before = last_day_of(y, m)

    total_before = Balance.total_balance_before(last_day_year_before)

    context['total_value'] = total_value
    context['total_before'] = total_before
    context['choose_year'] = year
    context['balances'] = balances
    context['years'] = Cash.list_years()
    context['section'] = 'cash_annual'

    return render(request, 'statement/cash_annual.html', context)

estofadora/statement/templates/statement/cash.html
{% extends "base.html" %}

{% block extra_js %} 
	<script src="http://malsup.github.com/jquery.form.js"></script>
{% endblock %}	

{% block title %}Caixa diário{% endblock title %}

{% block content-header-title %}
Caixa diário
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Receitas e despesas diarias.</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li class="active">Caixa</li>
<li class="active">Diário</li>
{% endblock content-header-breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Valor anterior</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
        <!-- /.box-tools -->
      </div>
      <!-- /.box-header -->
      <div class="box-body" style="display: block;">
        <div class="pull-left">
          {% if total_before > 0 %}
					<p class="text-right text-success">
					{% else %}
					<p class="text-right text-danger">
					{% endif %}
						Valor total anterior: R$ {{ total_before }}
					</p>
        </div>
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Receitas e despesas</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        <form method="POST" role="form" class="search-form">
          {% csrf_token %}
          <div class="form-inline">
            <input class="form-control" type="date" name="search_date" placeholder='Data para listar'>
            <span>
              <button class="btn btn-default form-control" type="submit" 
                name="search_form" id="search-btn">
                <i class="fa fa-search"></i>
                Listar
              </button>
            </span>
          </div>
        </form>
       	{% if content %}
          <table class="table table-striped">
					    <thead>
					        <tr>
					            <th>Data</th>
					            <th>Histórico</th>
					            <th>Entrada</th>
					            <th>Saida</th>
					            <th>Saldo</th>
					        </tr>
					    </thead>
					    <tbody>
					        {% for item in content %}
					            <tr>
					                <td>{{item.date}}</td>
					                <td>{{item.history}}</td>
					                <td>{{item.income}}</td>
					                <td>{{item.expenses }}</td>
					                <td>{{item.balance }}</td>
					                <th>
					                	<a href="{% url 'statement:delete' item.pk %}"
					                		title="remover item">
					                		<i class="fa fa-trash-o"></i>
					                	</a>
					                </th>
					            </tr>
					        {% endfor %}
					    </tbody>
					</table>
        {% else %}
          <div class="alert alert-warning text-center" role="alert">
            Nenhum registro encontrado na data: {{ choose_date }}!
          </div>
        {% endif %}
      </div>
      <!-- /.box-body -->
    </div>
    <div class="row">
      <div class="col-sm-12">
        {% if total_value > 0 %}
        <p class="text-right text-success">
        {% else %}
        <p class="text-right text-danger">
        {% endif %}
            Valor total de hoje: R$ {{ total_value }}
        </p>
      </div>
    </div>
    <!-- /.box -->
  </div>

  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Nova receita/despesa</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
        <!-- /.box-tools -->
      </div>
      <!-- /.box-header -->
    	<form  method="POST" role="form">
      	<div class="box-body" style="display: block;">
					{% csrf_token %}
			    {{ form.non_field_errors}}

			    {% for field in form %}
				    <div class="form-group">
					    {{ field.label_tag }}
					    {{ field }}
					    {{ field.errors }}
				    </div>
			    {% endfor %}
			  </div>
			  <div class="box-footer">
			    <button class="btn btn-primary" 
			    	type="submit" name="post_form">
			    	<i class="fa fa-plus-circle"></i>
			    	Inserir
			    </button>
			  </div>
			</form>
      </div>
      <!-- /.box-body -->
    </div>
  </div>
</div>

{% endblock %}

estofadora/statement/templates/statement/cash_annual.html
{% extends "base.html" %}	
{% load staticfiles %}

{% block title %}Caixa anual{% endblock title %}

{% block content-header-title %}
Caixa anual
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Receitas e despesas anuais.</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li class="active">Caixa</li>
<li class="active">Anual</li>
{% endblock content-header-breadcrumb %}

{% block content %}
<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Valor anterior</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
        <!-- /.box-tools -->
      </div>
      <!-- /.box-header -->
      <div class="box-body" style="display: block;">
        <div class="pull-left">
          {% if total_before > 0 %}
          <p class="text-right text-success">
          {% else %}
          <p class="text-right text-danger">
          {% endif %}
              Valor total de {{choose_year|add:"-1"}}: R$ {{ total_before }}
          </p>
        </div>
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Receitas e despesas</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive">
        {% if years %}
          <form method="POST" role="form" class="search-form">
                {% csrf_token %}
                <div class="form-inline">
              <select name="selectyear" class="form-control">
                {% for year in years %}
                  <option value="{{year}}"
                    {% if year == choose_year %}selected{% endif %}>
                    {{year}}
                  </option> 
                {% endfor %}
              </select>
              <span>
                <button class="btn btn-default form-control" type="submit" 
                  name="search_form" id="search-btn">
                  <i class="fa fa-search"></i>
                  Listar
                </button>
              </span>
            </div>
          </form>
          <!-- Prepare a Dom with size (width and height) for ECharts -->
          <div id="mychart" style="height:600px"></div>
        {% else %}
          <div class="alert alert-warning text-center" role="alert">
            Nenhum registro encontrado.
          </div>
        {% endif %}
      </div>
      <!-- /.box-body -->
    </div>
    <div class="row">
      <div class="col-sm-12">
        {% if total_value > 0 %}
        <p class="text-right text-success">
        {% else %}
        <p class="text-right text-danger">
        {% endif %}
            Valor total de {{choose_year}}: R$ {{ total_value }}
        </p>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>


<!-- ECharts import -->
<script src="{% static "js/echarts.js" %}"></script>
<script type="text/javascript">
    // configure for module loader
    require.config({
        paths: {
            echarts: 'http://echarts.baidu.com/build/dist'
        }
    });
    
    // use
    require(
        [
            'echarts',
            'echarts/chart/bar' // require the specific chart type
        ],
        function (ec) {
            // Initialize after dom ready
            var myChart = ec.init(document.getElementById('mychart')); 
            
            var option = {
                tooltip: {
                    show: true
                },
                legend: {
                    data:['Saldo']
                },
                xAxis : [
                    {
                        type : 'category',
                        data : ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]
                    }
                ],
                yAxis : [
                    {
                        type : 'value'
                    }
                ],
                series : [
                    {
                        "name":"Saldo",
                        "type":"bar",
                        "data": {{balances}} 
                    }
                ],
            };
    
            // Load data into the ECharts instance 
            myChart.setOption(option); 
        }
    );
</script>

{% endblock %}

estofadora/statement/templates/statement/cash_month.html
{% extends "base.html" %}	

{% block title %}Caixa mensal{% endblock title %}

{% block content-header-title %}
Caixa mensal
{% endblock content-header-title %}

{% block content-header-subtitle %}
<small>Receitas e despesas mensais.</small>
{% endblock content-header-subtitle %}

{% block content-header-breadcrumb %}
<li class="active">Caixa</li>
<li class="active">Mensal</li>
{% endblock content-header-breadcrumb %}

{% block content %}
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
		  <div class="box-header with-border">
		    <h3 class="box-title">Valor anterior</h3>

		    <div class="box-tools pull-right">
		      <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
		      </button>
		    </div>
		    <!-- /.box-tools -->
		  </div>
		  <!-- /.box-header -->
		  <div class="box-body" style="display: block;">
		    <div class="pull-left">
				  {% if total_before > 0 %}
					  <p class="text-right text-success">
				  {% else %}
				  	<p class="text-right text-danger">
				  {% endif %}
				  Valor total anterior: R$ {{ total_before }}
					</p>
				</div>
		  </div>
		  <!-- /.box-body -->
		</div>
	</div>
	<div class="col-xs-12">
		  <div class="box box-primary">
		    <div class="box-header">
		      <h3 class="box-title">Receitas e despesas</h3>
		    </div>
		    <!-- /.box-header -->
		    <div class="box-body table-responsive">
		    	{% if years %}
						<form method="POST" role="form" class="search-form">
					        {% csrf_token %}
					        <div class="form-inline">
			        	<select name="selectmonth" class="form-control">
			        		{% for number, name in months %}
				        		<option value="{{number}}"
				        			{% if number == choose_month %}selected{% endif %}>
											{{name}}
										</option>
			        		{% endfor %}
								</select>
			        	<select name="selectyear" class="form-control">
			        		{% for year in years %}
										<option value="{{year}}"
											{% if year == choose_year %}selected{% endif %}>
											{{year}}
										</option> 
				        		{% endfor %}
								</select>
			            <span>
		                <button class="btn btn-default form-control" type="submit" 
		                	name="search_form" id="search-btn">
		                	<i class="fa fa-search"></i>
		                	Listar
		                </button>
			            </span>
			        </div>
					  </form>
				    <table class="table table-hover">
				      {% if content %}
				        <thead>
					        <tr>
					          <th>#</th>
					          <th>Data</th>
				            <th>Histórico</th>
				            <th>Entrada</th>
				            <th>Saida</th>
				            <th>Saldo</th>
					        </tr>
					      </thead>
					      <tbody>
					      	{% for item in content %}
				            <tr>
				            	<td>{{forloop.counter}}</td>
				              <td>{{item.date}}</td>
				              <td>{{item.history}}</td>
				              <td>{{item.income}}</td>
				              <td>{{item.expenses }}</td>
				              <td>{{item.balance }}</td>
				            </tr>
				        {% endfor %}
				        </tbody>
				      {% else %}
						  	<div class="alert alert-warning text-center" role="alert">
						  		Nenhum registro encontrado.
						  	</div>
							{% endif %}
				   	</table>
	      	{% else %}
				  	<div class="alert alert-warning text-center" role="alert">
				  		Nenhum registro encontrado.
				  	</div>
					{% endif %}
		    </div>
		    <!-- /.box-body -->
		  </div>
		  <div class="row">
	     	<div class="col-sm-12">
	     		{% if total_value > 0 %}
						<p class="text-right text-success">
					{% else %}
						<p class="text-right text-danger">
					{% endif %}
					Valor total: R$ {{ total_value }}
					</p>
	     	</div>
	   	</div>
	  <!-- /.box -->
	</div>
</div>

{% endblock %}

estofadora/statement/templates/statement/item_edit_form.html
{% if form_error %}
<div class="modal-dialog"> 
	<div class="modal-content">
{% endif %}
		<div class="modal-header"> 
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> 
			<h4 class="modal-title" id="myModalLabel">Editar item</h4> 
		</div> 
		<form id="item_update_form" method='post' class="form" role="form" action="{% url 'statement:edit' item.id %}"> 
			<div class="modal-body"> 
				{% csrf_token %} 
				{{ form.non_field_errors }} 
				{% for field in form %}
				    <div class="form-group">
					    {{ field.label_tag }}
					    {{ field }}
					    {{ field.errors }}
				    </div>
	    		{% endfor %} 
			</div> 
			<div class="modal-footer"> 
				<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar" aria-hidden="true" /> 
				<input type="submit" class="btn btn-primary" value="Editar" style="margin-bottom: 5px;" /> 
			</div> 
		</form> 
		<script> 
			//jQuery('.modal-content .calendar').datepicker({ dateFormat: "yy-mm-dd" }); 
			var form_options = { 
				target: '#modal', 
				success: function() { } 
			} 
			$('#item_update_form').ajaxForm(form_options);
			</script> 
{% if form_error %}
	</div>
</div>
{% endif %}

estofadora/statement/templates/statement/item_edit_form_success.html
<div class="modal-dialog modal-lg"> 
	<div class="modal-content">
		<div class="modal-header"> 
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> 
			<h4 class="modal-title" id="myModalLabel">Aviso</h4> 
		</div> 	
		<div class="modal-body"> 
			<p>Item alterado com sucesso!</p> 
			<script> 
				//setTimeout(function() { jQuery('#modal').modal('hide'); }, 1000);
				$('body').on('hidden.bs.modal', '.modal', function () { 
					$(this).removeData('bs.modal'); }); 
			</script> 
		</div>
		<div class="modal-footer"></div> 
	</div>
</div>

estofadora/statement/templates/statement/statement.html
{% extends "base.html" %}

{% block content %}
<div class="panel panel-default">
	<div class="panel-body">
		<h3><p class="text-center">Relatórios</p></h3>
	</div>
</div>

<div class="list-group">
  <a href="{% url 'statement:cash' %}" class="list-group-item">Caixa diário</a>
</div>

{% endblock %}